#!/usr/bin/env bash
# cript that generates a MySQL dump and creates a compressed archive out of it
#  MySQL dump must contain all your MySQL databases
# The MySQL dump must be named backup.sql
# The MySQL dump file has to be compressed to a tar.gz archive
# This archive must have the following name format: day-month-year.tar.gz
# The user to connect to the MySQL database must be root
mysqldump -uroot -p"$1" --all-databases > backup.sql
tar czf "$(date +"%d-%m-%Y").tar.gz" backup.sql
