#!/usr/bin/env bash
#comment

echo "$$" > /var/run/holbertonscript.pid
trap "echo Y U no love me?!; exit" SIGINT
trap "echo I hate the kill command" SIGTERM
trap "rm /var/run/holbertonscript.pid; exit" SIGQUIT SIGTERMi

for (( ; ; ));do
echo "To infinity and beyond"
sleep 2
done
