#!/usr/bin/env bash
#comment

echo "$$" > /var/run/myscript.pid
trap "echo Y U no love me?!" SIGINT
trap "echo I hate the kill command" SIGTERM
trap "rm /var/run/myscript.pid; kill -s KILL "$$"" SIGQUIT SIGTERM

for (( ; ; ));do
echo "To infinity and beyond"
done
