#!/usr/bin/env bash
#This script prints out seq of 1-100, if multiple of 5 print Buzz, if multiple of 3 print Fizz, if multiple of both print FizzBuzz

for (( i=1; i<=100; i++ ))
do
	if [[ $((i%3)) == 0 &&  $((i%5)) == 0 ]]
	then
		echo "FizzBuzz"
	elif [[ $((i%3)) == 0 ]];then
	echo "Fizz"	
	elif [[ $((i%5)) == 0 ]];then
		echo "Buzz"
else
		echo $i
	fi
done	
